name: deploy builder container image

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  REPO: ghcr.io/${{ github.repository }}-builder
  VERSION: 1.1

jobs:
  deploy-builder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set environment DOCKERHUB_IMAGE_PLATFORMS
        run: |
          _DOCKERHUB_IMAGE_PLATFORMS="linux/amd64,linux/arm64"
          echo "DOCKERHUB_IMAGE_PLATFORMS=$_DOCKERHUB_IMAGE_PLATFORMS" >> $GITHUB_ENV

      - name: Build and push Docker image Trace
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.builder
          push: true
          platforms: ${{ env.DOCKERHUB_IMAGE_PLATFORMS }}
          tags: ${{ env.REPO }}:latest,${{ env.REPO }}:${{ env.VERSION }}
